/**
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

const mockProperties = [
  {
    id: 1,
    city: "Seattle",
    title: "Luxury Condo in Belltown",
    price: 1550000,
    type: "Apartment",
    area: 1250,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Walk-in Closets",
      "Bike Storage",
      "Doorman",
      "Solar Panels",
      "EV Charging Station",
      "Garage Parking",
      "High Ceilings",
      "Balcony",
      "Elevator",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    address: "98121 Seattle, WA",
    lat: 47.6145,
    lng: -122.3486,
    description: "Stunning high-rise condo with Elliott Bay views. Floor-to-ceiling windows, chef's kitchen, and 24/7 concierge.",
    link: "#"
  },
  {
    id: 2,
    city: "Seattle",
    title: "Cozy Capitol Hill Studio",
    price: 380000,
    type: "Studio",
    area: 450,
    rooms: 1,
    bedrooms: 0,
    features: [
      "Balcony",
      "Furnished",
      "Water View",
      "Central AC",
      "Doorman",
      "In-unit Washer/Dryer",
      "Hardwood Floors",
      "Swimming Pool",
      "Solar Panels",
      "Rooftop Deck",
      "Pet Friendly",
      "Private Terrace",
      "Finished Basement",
      "Fireplace",
      "Walk-in Closets",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "98122 Seattle, WA",
    lat: 47.6152,
    lng: -122.3182,
    description: "Perfect pied-à-terre in the heart of Capitol Hill. Steps away from light rail, cafes, and nightlife.",
    link: "#"
  },
  {
    id: 3,
    city: "Seattle",
    title: "Modern Townhome in Ballard",
    price: 1100000,
    type: "House",
    area: 1600,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Doorman",
      "Finished Basement",
      "Dishwasher",
      "Water View",
      "Hardwood Floors",
      "Fitness Center",
      "Walk-in Closets",
      "Private Terrace",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800",
    address: "98107 Seattle, WA",
    lat: 47.6686,
    lng: -122.3847,
    description: "Contemporary Built Green townhome featuring a rooftop deck with mountain views and dedicated off-street parking.",
    link: "#"
  },
  {
    id: 4,
    city: "Seattle",
    title: "Classic Craftsman in Queen Anne",
    price: 2400000,
    type: "House",
    area: 3200,
    rooms: 8,
    bedrooms: 4,
    features: [
      "Spa & Sauna",
      "Pet Friendly",
      "Smart Home System",
      "Private Terrace",
      "Concierge Service",
      "Garage Parking",
      "Secure Package Room",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
    address: "98109 Seattle, WA",
    lat: 47.6335,
    lng: -122.3571,
    description: "Meticulously restored historic Craftsman on a coveted Queen Anne street. Massive wrap-around porch and mature garden.",
    link: "#"
  },
  {
    id: 5,
    city: "Seattle",
    title: "Spacious Condo on First Hill",
    price: 950000,
    type: "Apartment",
    area: 1400,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Co-working Space",
      "Water View",
      "Furnished",
      "Elevator",
      "Finished Basement",
      "Spa & Sauna",
      "Fitness Center",
      "Solar Panels",
      "Hardwood Floors",
      "Dishwasher",
      "Secure Package Room",
      "Rooftop Deck",
      "Garage Parking",
      "Floor-to-Ceiling Windows"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "98104 Seattle, WA",
    lat: 47.6083,
    lng: -122.3243,
    description: "Bright corner unit walking distance to hospitals and downtown. Great value with secure garage parking included.",
    link: "#"
  },
  {
    id: 6,
    city: "Seattle",
    title: "U-District Student Studio",
    price: 310000,
    type: "Studio",
    area: 380,
    rooms: 1,
    bedrooms: 0,
    features: [
      "Solar Panels",
      "Central AC",
      "Rooftop Deck",
      "High Ceilings",
      "Garage Parking",
      "Elevator",
      "Swimming Pool",
      "Water View",
      "Spa & Sauna",
      "Pet Friendly",
      "EV Charging Station",
      "In-unit Washer/Dryer",
      "Wheelchair Accessible",
      "Fenced Yard"
    ],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800",
    address: "98105 Seattle, WA",
    lat: 47.6599,
    lng: -122.3134,
    description: "Excellent investment blocks from the University of Washington campus. Low HOA dues and high rentability.",
    link: "#"
  },
  {
    id: 7,
    city: "Seattle",
    title: "Penthouse in South Lake Union",
    price: 3200000,
    type: "Apartment",
    area: 2800,
    rooms: 6,
    bedrooms: 3,
    features: [
      "Newly Renovated",
      "Hardwood Floors",
      "Smart Home System",
      "Walk-in Closets",
      "Co-working Space",
      "In-unit Washer/Dryer",
      "Balcony",
      "Elevator",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800",
    address: "98109 Seattle, WA",
    lat: 47.6253,
    lng: -122.3364,
    description: "Breathtaking penthouse above SLU. Wrap-around terrace overlooking Lake Union and the Space Needle.",
    link: "#"
  },
  {
    id: 8,
    city: "Seattle",
    title: "Industrial Loft in Pioneer Square",
    price: 850000,
    type: "Apartment",
    area: 1100,
    rooms: 2,
    bedrooms: 1,
    features: [
      "Doorman",
      "Balcony",
      "Solar Panels",
      "Fenced Yard",
      "Smart Home System",
      "Elevator",
      "EV Charging Station",
      "Wheelchair Accessible",
      "Spa & Sauna",
      "Garage Parking"
    ],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
    address: "98104 Seattle, WA",
    lat: 47.6015,
    lng: -122.3331,
    description: "Historic loft with exposed brick walls, timber beams, and soaring 14-foot ceilings. A true creative space.",
    link: "#"
  },
  {
    id: 9,
    city: "Seattle",
    title: "Quiet Bungalow in Green Lake",
    price: 1150000,
    type: "House",
    area: 1850,
    rooms: 6,
    bedrooms: 3,
    features: [
      "Doorman",
      "Co-working Space",
      "Furnished",
      "Balcony",
      "EV Charging Station",
      "Walk-in Closets",
      "Elevator",
      "Newly Renovated",
      "Secure Package Room",
      "Rooftop Deck",
      "Smart Home System"
    ],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    address: "98115 Seattle, WA",
    lat: 47.6816,
    lng: -122.3275,
    description: "Charming updated bungalow just two blocks from Green Lake park. Features a sunny backyard and detached garage.",
    link: "#"
  },
  {
    id: 10,
    city: "Seattle",
    title: "Waterfront Condo in Madison Park",
    price: 2800000,
    type: "Apartment",
    area: 2100,
    rooms: 5,
    bedrooms: 2,
    features: [
      "Private Terrace",
      "Hardwood Floors",
      "Doorman",
      "EV Charging Station",
      "Concierge Service",
      "Garage Parking",
      "Balcony",
      "Finished Basement",
      "Elevator",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800",
    address: "98112 Seattle, WA",
    lat: 47.6356,
    lng: -122.2801,
    description: "Luxury living on Lake Washington. Private boat slip included, along with panoramic views of the water and mountains.",
    link: "#"
  },
  {
    id: 11,
    city: "Seattle",
    title: "Bright Studio near Alki Beach",
    price: 420000,
    type: "Studio",
    area: 500,
    rooms: 1,
    bedrooms: 0,
    features: [
      "Pet Friendly",
      "Swimming Pool",
      "Elevator",
      "Spa & Sauna",
      "Finished Basement",
      "Fenced Yard",
      "Hardwood Floors",
      "Central AC",
      "Solar Panels",
      "Water View",
      "Fireplace"
    ],
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=800",
    address: "98116 Seattle, WA",
    lat: 47.5794,
    lng: -122.4106,
    description: "Top floor studio in West Seattle just steps from Alki beach. Includes one parking spot and storage unit.",
    link: "#"
  },
  {
    id: 12,
    city: "Seattle",
    title: "New Townhome in Columbia City",
    price: 780000,
    type: "House",
    area: 1450,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Doorman",
      "Swimming Pool",
      "Solar Panels",
      "Balcony",
      "Fitness Center",
      "Fireplace",
      "Bike Storage",
      "Rooftop Deck",
      "Pet Friendly",
      "Spa & Sauna",
      "Hardwood Floors",
      "EV Charging Station",
      "Water View",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800",
    address: "98118 Seattle, WA",
    lat: 47.5604,
    lng: -122.2871,
    description: "Eco-friendly modern townhome. Mini-splits provide efficient heating/cooling. Close to Columbia City light rail station.",
    link: "#"
  },
  {
    id: 13,
    city: "Seattle",
    title: "Mid-Century Modern in Magnolia",
    price: 1650000,
    type: "House",
    area: 2400,
    rooms: 7,
    bedrooms: 4,
    features: [
      "Central AC",
      "In-unit Washer/Dryer",
      "Garage Parking",
      "Hardwood Floors",
      "Floor-to-Ceiling Windows",
      "Private Terrace",
      "Fenced Yard",
      "Solar Panels",
      "Concierge Service",
      "Finished Basement",
      "EV Charging Station",
      "Wheelchair Accessible",
      "Fireplace",
      "High Ceilings",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800",
    address: "98199 Seattle, WA",
    lat: 47.6394,
    lng: -122.3995,
    description: "Stunning 1960s architecture with sweeping views of the Puget Sound and Olympic Mountains. Floor to ceiling glass.",
    link: "#"
  },
  {
    id: 14,
    city: "Seattle",
    title: "Architectural Marvel in Laurelhurst",
    price: 4150000,
    type: "House",
    area: 5200,
    rooms: 10,
    bedrooms: 5,
    features: [
      "City View",
      "Floor-to-Ceiling Windows",
      "Elevator",
      "Co-working Space",
      "High Ceilings",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&q=80&w=800",
    address: "98105 Seattle, WA",
    lat: 47.6596,
    lng: -122.2743,
    description: "Private compound in exclusive Laurelhurst. Features an indoor pool, home theater, and expansive manicured grounds.",
    link: "#"
  },
  {
    id: 15,
    city: "Seattle",
    title: "Downtown Seattle High-Rise",
    price: 2150000,
    type: "Apartment",
    area: 1800,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Hardwood Floors",
      "Fireplace",
      "Balcony",
      "High Ceilings",
      "Garage Parking",
      "Furnished",
      "Private Terrace",
      "Bike Storage",
      "Concierge Service",
      "Water View",
      "Rooftop Deck",
      "Walk-in Closets",
      "Finished Basement",
      "City View",
      "Elevator",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&q=80&w=800",
    address: "98101 Seattle, WA",
    lat: 47.6101,
    lng: -122.3344,
    description: "Luxury 35th-floor living above Pacific Place. Unobstructed city skyline views, 5-star building amenities.",
    link: "#"
  },
  {
    id: 16,
    city: "Seattle",
    title: "Large Family Home in Wallingford",
    price: 1850000,
    type: "House",
    area: 3100,
    rooms: 8,
    bedrooms: 5,
    features: [
      "In-unit Washer/Dryer",
      "Rooftop Deck",
      "Smart Home System",
      "EV Charging Station",
      "Central AC",
      "Solar Panels",
      "Newly Renovated",
      "Home Office",
      "Bike Storage",
      "Dishwasher"
    ],
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
    address: "98103 Seattle, WA",
    lat: 47.6595,
    lng: -122.3353,
    description: "Fully remodeled classic home in heart of Wallingford. Great schools, large basement play area, and huge front porch.",
    link: "#"
  },
  {
    id: 17,
    city: "Seattle",
    title: "Live/Work Studio in Fremont",
    price: 595000,
    type: "Studio",
    area: 850,
    rooms: 1,
    bedrooms: 0,
    features: [
      "Co-working Space",
      "Fitness Center",
      "Balcony",
      "Secure Package Room",
      "Doorman",
      "Fenced Yard",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80&w=800",
    address: "98103 Seattle, WA",
    lat: 47.6511,
    lng: -122.3498,
    description: "Unique open-concept space in the Center of the Universe. Commercial zoning allowed. Perfect for artist or small business.",
    link: "#"
  },
  {
    id: 18,
    city: "Seattle",
    title: "Charming Condo in Mount Baker",
    price: 680000,
    type: "Apartment",
    area: 950,
    rooms: 3,
    bedrooms: 2,
    features: [
      "Fireplace",
      "Finished Basement",
      "Secure Package Room",
      "High Ceilings",
      "Central AC",
      "Solar Panels",
      "Furnished",
      "Bike Storage",
      "Floor-to-Ceiling Windows",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    address: "98144 Seattle, WA",
    lat: 47.5768,
    lng: -122.2891,
    description: "Quiet lake-view unit near Mount Baker beach. Updated kitchen, hardwood floors, and a sunny east-facing deck.",
    link: "#"
  },
  {
    id: 19,
    city: "Seattle",
    title: "Modern Estate in Broadmoor",
    price: 5200000,
    type: "House",
    area: 6000,
    rooms: 12,
    bedrooms: 6,
    features: [
      "In-unit Washer/Dryer",
      "Bike Storage",
      "EV Charging Station",
      "Walk-in Closets",
      "Home Office",
      "Balcony",
      "Newly Renovated",
      "Private Terrace",
      "City View",
      "Swimming Pool",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    address: "98112 Seattle, WA",
    lat: 47.6358,
    lng: -122.2922,
    description: "Incredible new construction inside the Broadmoor gated community. Features a golf simulator, wine cellar, and guest house.",
    link: "#"
  },
  {
    id: 20,
    city: "Seattle",
    title: "Lake Union Houseboat",
    price: 1250000,
    type: "House",
    area: 1200,
    rooms: 3,
    bedrooms: 1,
    features: [
      "Concierge Service",
      "Water View",
      "Solar Panels",
      "Smart Home System",
      "Elevator",
      "Doorman",
      "Garage Parking",
      "Finished Basement",
      "Furnished",
      "Fireplace"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "98109 Seattle, WA",
    lat: 47.6373,
    lng: -122.3338,
    description: "Sleepless in Seattle style floating home. Launch your paddleboard directly from the living room deck.",
    link: "#"
  },
  {
    id: 21,
    city: "Seattle",
    title: "Sleek Condo in Denny Triangle",
    price: 920000,
    type: "Condominium",
    area: 980,
    rooms: 3,
    bedrooms: 2,
    features: [
      "Co-working Space",
      "City View",
      "Water View",
      "In-unit Washer/Dryer",
      "Rooftop Deck",
      "Swimming Pool",
      "Secure Package Room",
      "Elevator",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800",
    address: "98121 Seattle, WA",
    lat: 47.616,
    lng: -122.337,
    description: "Modern high-rise condo right near Amazon HQ. Floor-to-ceiling windows and premium appliances.",
    link: "#"
  },
  {
    id: 22,
    city: "Seattle",
    title: "Historic Brick House in Madison Valley",
    price: 1350000,
    type: "House",
    area: 2100,
    rooms: 6,
    bedrooms: 3,
    features: [
      "Furnished",
      "EV Charging Station",
      "Central AC",
      "Pet Friendly",
      "Co-working Space"
    ],
    image: "https://images.unsplash.com/photo-1549517045-bc93de0cecb6?auto=format&fit=crop&q=80&w=800",
    address: "98112 Seattle, WA",
    lat: 47.6258,
    lng: -122.2965,
    description: "Beautifully preserved 1920s brick home with original oak floors, leaded glass, and a detached garage.",
    link: "#"
  },
  {
    id: 23,
    city: "Seattle",
    title: "Luxury Penthouse in Pioneer Square",
    price: 2400000,
    type: "Apartment",
    area: 2500,
    rooms: 5,
    bedrooms: 2,
    features: [
      "Finished Basement",
      "Hardwood Floors",
      "Home Office",
      "Concierge Service",
      "Rooftop Deck",
      "Dishwasher",
      "Water View",
      "Secure Package Room",
      "Newly Renovated",
      "Pet Friendly",
      "Solar Panels",
      "Wheelchair Accessible",
      "Co-working Space",
      "Bike Storage",
      "Furnished",
      "Elevator",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "98104 Seattle, WA",
    lat: 47.6,
    lng: -122.332,
    description: "Expansive penthouse featuring an enormous private rooftop deck overlooking the stadiums and Puget Sound.",
    link: "#"
  },
  {
    id: 24,
    city: "Seattle",
    title: "Cute Cottage in Phinney Ridge",
    price: 890000,
    type: "House",
    area: 1200,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Co-working Space",
      "Finished Basement",
      "Garage Parking",
      "Balcony",
      "Elevator",
      "Doorman",
      "Walk-in Closets",
      "Dishwasher",
      "Home Office",
      "Fenced Yard",
      "Furnished",
      "Private Terrace"
    ],
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80&w=800",
    address: "98103 Seattle, WA",
    lat: 47.674,
    lng: -122.3551,
    description: "Charming cottage near the zoo. Fully fenced yard, cozy fireplace, and views of the Olympic mountains from the front deck.",
    link: "#"
  },
  {
    id: 25,
    city: "Seattle",
    title: "Waterfront Townhouse in Eastlake",
    price: 1750000,
    type: "Townhouse",
    area: 1900,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Pet Friendly",
      "Newly Renovated",
      "Elevator",
      "Fitness Center",
      "Co-working Space",
      "Secure Package Room",
      "Hardwood Floors",
      "Balcony",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&q=80&w=800",
    address: "98102 Seattle, WA",
    lat: 47.641,
    lng: -122.325,
    description: "Live steps from Lake Union. Multi-level townhouse with private moorage access, A/C, and attached garage.",
    link: "#"
  },
  {
    id: 26,
    city: "Seattle",
    title: "Investment Duplex in Beacon Hill",
    price: 1100000,
    type: "House",
    area: 2200,
    rooms: 8,
    bedrooms: 4,
    features: [
      "Dishwasher",
      "Central AC",
      "Furnished",
      "Elevator",
      "Garage Parking",
      "Spa & Sauna",
      "Smart Home System",
      "Secure Package Room"
    ],
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800",
    address: "98144 Seattle, WA",
    lat: 47.579,
    lng: -122.311,
    description: "Rare side-by-side duplex with great rental history. Quick access to I-5 and walking distance to Jefferson Park.",
    link: "#"
  },
  {
    id: 27,
    city: "Seattle",
    title: "Corner Unit Condo in Lower Queen Anne",
    price: 650000,
    type: "Condominium",
    area: 850,
    rooms: 3,
    bedrooms: 1,
    features: [
      "Hardwood Floors",
      "In-unit Washer/Dryer",
      "Private Terrace",
      "Fireplace",
      "Newly Renovated",
      "Wheelchair Accessible",
      "Elevator",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800",
    address: "98109 Seattle, WA",
    lat: 47.6231,
    lng: -122.355,
    description: "Steps from Seattle Center and Climate Pledge Arena. Bright corner unit with Space Needle views.",
    link: "#"
  },
  {
    id: 28,
    city: "Seattle",
    title: "Brand New Construction in West Seattle",
    price: 1450000,
    type: "House",
    area: 2600,
    rooms: 7,
    bedrooms: 4,
    features: [
      "Dishwasher",
      "Wheelchair Accessible",
      "Garage Parking",
      "Concierge Service",
      "Balcony",
      "Hardwood Floors",
      "Elevator",
      "Fitness Center",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
    address: "98116 Seattle, WA",
    lat: 47.57,
    lng: -122.385,
    description: "Stunning modern home with smart-home features throughout. Huge rooftop deck and a heated 2-car garage.",
    link: "#"
  },
  {
    id: 29,
    city: "Seattle",
    title: "Spacious Loft in Sodo",
    price: 720000,
    type: "Studio",
    area: 1300,
    rooms: 2,
    bedrooms: 1,
    features: [
      "Hardwood Floors",
      "Fenced Yard",
      "Secure Package Room",
      "Bike Storage",
      "Fitness Center",
      "Central AC",
      "Floor-to-Ceiling Windows",
      "Water View",
      "Fireplace",
      "Co-working Space",
      "Balcony",
      "High Ceilings",
      "Wheelchair Accessible",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800",
    address: "98134 Seattle, WA",
    lat: 47.585,
    lng: -122.3325,
    description: "Authentic industrial loft space offering massive square footage, concrete floors, and flexible zoning.",
    link: "#"
  },
  {
    id: 30,
    city: "Seattle",
    title: "Treehouse Cabin in Seward Park",
    price: 1100000,
    type: "House",
    area: 1700,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Central AC",
      "Balcony",
      "Fenced Yard",
      "Concierge Service",
      "Rooftop Deck",
      "Solar Panels",
      "Bike Storage",
      "Finished Basement",
      "Floor-to-Ceiling Windows",
      "Hardwood Floors",
      "Fitness Center",
      "Smart Home System",
      "Secure Package Room",
      "Garage Parking",
      "Newly Renovated"
    ],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    address: "98118 Seattle, WA",
    lat: 47.55,
    lng: -122.261,
    description: "A private oasis tucked into the trees. Mid-century cabin feel, just blocks away from Lake Washington and Seward Park.",
    link: "#"
  },
  {
    id: 31,
    city: "Seattle",
    title: "Sunlit Condo in South Lake Union",
    price: 850000,
    type: "Apartment",
    area: 1050,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Elevator",
      "Walk-in Closets",
      "Newly Renovated",
      "High Ceilings",
      "Rooftop Deck",
      "Garage Parking",
      "City View",
      "Bike Storage",
      "Solar Panels",
      "Floor-to-Ceiling Windows",
      "Furnished",
      "Balcony",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
    address: "98109 Seattle, WA",
    lat: 47.62,
    lng: -122.335,
    description: "Modern 2-bedroom condo with a private balcony facing the lake. Enjoy city living with incredible amenities.",
    link: "#"
  },
  {
    id: 32,
    city: "Seattle",
    title: "Quiet Retreat in Queen Anne",
    price: 895000,
    type: "Apartment",
    area: 1200,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Wheelchair Accessible",
      "Central AC",
      "High Ceilings",
      "Dishwasher",
      "Co-working Space",
      "Smart Home System",
      "Concierge Service",
      "Secure Package Room",
      "Elevator",
      "Spa & Sauna",
      "In-unit Washer/Dryer",
      "Fireplace",
      "City View",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800",
    address: "98119 Seattle, WA",
    lat: 47.63,
    lng: -122.36,
    description: "Spacious three-bedroom apartment in a peaceful neighborhood, featuring a large balcony perfect for summer evenings.",
    link: "#"
  },
  {
    id: 33,
    city: "Seattle",
    title: "Vibrant Capitol Hill Flat",
    price: 780000,
    type: "Apartment",
    area: 950,
    rooms: 3,
    bedrooms: 2,
    features: [
      "Fitness Center",
      "Doorman",
      "Dishwasher",
      "Rooftop Deck",
      "City View",
      "Fireplace",
      "Finished Basement",
      "Private Terrace",
      "Hardwood Floors",
      "Fenced Yard",
      "Furnished",
      "Water View",
      "Concierge Service",
      "Newly Renovated",
      "Balcony",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=800",
    address: "98122 Seattle, WA",
    lat: 47.618,
    lng: -122.32,
    description: "Right in the heart of the action. This modern flat offers two bedrooms and a nice balcony for people-watching.",
    link: "#"
  },
  {
    id: 34,
    city: "Austin",
    title: "House in Austin",
    price: 746430,
    type: "House",
    area: 2030,
    rooms: 6,
    bedrooms: 4,
    features: [
      "Swimming Pool",
      "High Ceilings",
      "Balcony",
      "Smart Home System",
      "Concierge Service",
      "Wheelchair Accessible",
      "Furnished",
      "Private Terrace",
      "Newly Renovated",
      "Fireplace",
      "Fenced Yard",
      "Hardwood Floors",
      "Home Office",
      "Doorman",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    address: "100 Texas Ave, Austin, TX",
    lat: 30.221886217251292,
    lng: -97.78615854703854,
    description: "Fantastic house located in Austin.",
    link: "#"
  },
  {
    id: 35,
    city: "Austin",
    title: "Apartment in Austin",
    price: 615292,
    type: "Apartment",
    area: 1123,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Fitness Center",
      "Finished Basement",
      "Pet Friendly",
      "Central AC",
      "Co-working Space",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    address: "101 Texas Ave, Austin, TX",
    lat: 30.299265626725965,
    lng: -97.77925664099148,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 36,
    city: "Austin",
    title: "Apartment in Austin",
    price: 524369,
    type: "Apartment",
    area: 627,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Dishwasher",
      "Concierge Service",
      "EV Charging Station",
      "Fitness Center",
      "Finished Basement",
      "In-unit Washer/Dryer",
      "Garage Parking",
      "Doorman",
      "Hardwood Floors",
      "Newly Renovated",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "102 Texas Ave, Austin, TX",
    lat: 30.230411156684006,
    lng: -97.7133906544682,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 37,
    city: "Austin",
    title: "House in Austin",
    price: 392428,
    type: "House",
    area: 1267,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Bike Storage",
      "Secure Package Room",
      "Finished Basement",
      "Garage Parking",
      "In-unit Washer/Dryer",
      "Smart Home System",
      "Co-working Space",
      "Private Terrace",
      "Swimming Pool",
      "Concierge Service",
      "Home Office",
      "Spa & Sauna",
      "Central AC",
      "Elevator",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800",
    address: "103 Texas Ave, Austin, TX",
    lat: 30.292262246288786,
    lng: -97.78559394042071,
    description: "Fantastic house located in Austin.",
    link: "#"
  },
  {
    id: 38,
    city: "Austin",
    title: "Apartment in Austin",
    price: 338763,
    type: "Apartment",
    area: 892,
    rooms: 5,
    bedrooms: 3,
    features: [
      "City View",
      "Bike Storage",
      "Hardwood Floors",
      "Fireplace",
      "Pet Friendly",
      "High Ceilings",
      "Fitness Center",
      "Floor-to-Ceiling Windows",
      "Dishwasher",
      "Private Terrace",
      "Rooftop Deck",
      "Finished Basement",
      "Co-working Space",
      "Water View",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "104 Texas Ave, Austin, TX",
    lat: 30.214417653733904,
    lng: -97.72668092960822,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 39,
    city: "Austin",
    title: "Apartment in Austin",
    price: 523469,
    type: "Apartment",
    area: 1213,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Private Terrace",
      "Wheelchair Accessible",
      "Walk-in Closets",
      "Garage Parking",
      "Fitness Center",
      "Finished Basement",
      "Swimming Pool",
      "Newly Renovated",
      "Central AC",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "105 Texas Ave, Austin, TX",
    lat: 30.260285801479,
    lng: -97.71467091602511,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 40,
    city: "Austin",
    title: "House in Austin",
    price: 935013,
    type: "House",
    area: 2598,
    rooms: 3,
    bedrooms: 1,
    features: [
      "Newly Renovated",
      "Swimming Pool",
      "Balcony",
      "Dishwasher",
      "Doorman",
      "Central AC",
      "Bike Storage",
      "Fitness Center",
      "Floor-to-Ceiling Windows",
      "EV Charging Station",
      "Hardwood Floors",
      "Home Office",
      "Smart Home System"
    ],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
    address: "106 Texas Ave, Austin, TX",
    lat: 30.309673858706212,
    lng: -97.78860739419298,
    description: "Fantastic house located in Austin.",
    link: "#"
  },
  {
    id: 41,
    city: "Austin",
    title: "Apartment in Austin",
    price: 366843,
    type: "Apartment",
    area: 1384,
    rooms: 6,
    bedrooms: 4,
    features: [
      "Floor-to-Ceiling Windows",
      "Pet Friendly",
      "Balcony",
      "Smart Home System",
      "Rooftop Deck",
      "Private Terrace",
      "Secure Package Room",
      "Co-working Space",
      "Fitness Center",
      "Wheelchair Accessible",
      "Spa & Sauna",
      "Central AC",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "107 Texas Ave, Austin, TX",
    lat: 30.26778956351759,
    lng: -97.69452147574498,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 42,
    city: "Austin",
    title: "Apartment in Austin",
    price: 831720,
    type: "Apartment",
    area: 2024,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Newly Renovated",
      "Garage Parking",
      "High Ceilings",
      "Doorman",
      "EV Charging Station",
      "Solar Panels",
      "Furnished",
      "Concierge Service",
      "Rooftop Deck",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "108 Texas Ave, Austin, TX",
    lat: 30.287060851255532,
    lng: -97.7245996644866,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 43,
    city: "Austin",
    title: "House in Austin",
    price: 871649,
    type: "House",
    area: 868,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Floor-to-Ceiling Windows",
      "Garage Parking",
      "Balcony",
      "Furnished",
      "In-unit Washer/Dryer",
      "Newly Renovated",
      "High Ceilings",
      "Fenced Yard",
      "Home Office",
      "Finished Basement",
      "Concierge Service",
      "Central AC",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    address: "109 Texas Ave, Austin, TX",
    lat: 30.29154969078501,
    lng: -97.75129739075004,
    description: "Fantastic house located in Austin.",
    link: "#"
  },
  {
    id: 44,
    city: "Austin",
    title: "Apartment in Austin",
    price: 902029,
    type: "Apartment",
    area: 1770,
    rooms: 6,
    bedrooms: 4,
    features: [
      "Doorman",
      "Garage Parking",
      "City View",
      "Bike Storage",
      "Furnished",
      "High Ceilings",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "1010 Texas Ave, Austin, TX",
    lat: 30.24098973171774,
    lng: -97.71941649941988,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 45,
    city: "Austin",
    title: "Apartment in Austin",
    price: 416388,
    type: "Apartment",
    area: 608,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Floor-to-Ceiling Windows",
      "Swimming Pool",
      "Secure Package Room",
      "Newly Renovated",
      "Concierge Service",
      "Central AC",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "1011 Texas Ave, Austin, TX",
    lat: 30.282964479939725,
    lng: -97.71151294925362,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 46,
    city: "Austin",
    title: "House in Austin",
    price: 929109,
    type: "House",
    area: 1523,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Hardwood Floors",
      "Central AC",
      "Finished Basement",
      "Newly Renovated",
      "High Ceilings",
      "Fitness Center",
      "Balcony",
      "Wheelchair Accessible",
      "Furnished",
      "Rooftop Deck",
      "Secure Package Room",
      "Water View"
    ],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
    address: "1012 Texas Ave, Austin, TX",
    lat: 30.221783951557764,
    lng: -97.69627202871203,
    description: "Fantastic house located in Austin.",
    link: "#"
  },
  {
    id: 47,
    city: "Austin",
    title: "Apartment in Austin",
    price: 561987,
    type: "Apartment",
    area: 2550,
    rooms: 6,
    bedrooms: 4,
    features: [
      "Elevator",
      "Balcony",
      "High Ceilings",
      "Wheelchair Accessible",
      "Finished Basement",
      "Fenced Yard",
      "Concierge Service",
      "Home Office",
      "Swimming Pool",
      "Newly Renovated",
      "City View",
      "Rooftop Deck",
      "Bike Storage",
      "Fireplace",
      "Water View",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "1013 Texas Ave, Austin, TX",
    lat: 30.288771660124706,
    lng: -97.69618705235501,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 48,
    city: "Austin",
    title: "Apartment in Austin",
    price: 494820,
    type: "Apartment",
    area: 1479,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Swimming Pool",
      "Pet Friendly",
      "Garage Parking",
      "Co-working Space",
      "Hardwood Floors",
      "Central AC",
      "Solar Panels",
      "Fireplace",
      "Concierge Service",
      "High Ceilings",
      "Newly Renovated",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "1014 Texas Ave, Austin, TX",
    lat: 30.26961462125363,
    lng: -97.77877110299553,
    description: "Fantastic apartment located in Austin.",
    link: "#"
  },
  {
    id: 49,
    city: "Miami",
    title: "Condominium in Miami",
    price: 909071,
    type: "Condominium",
    area: 2867,
    rooms: 6,
    bedrooms: 4,
    features: [
      "Walk-in Closets",
      "City View",
      "Dishwasher",
      "Wheelchair Accessible",
      "EV Charging Station",
      "Fenced Yard",
      "Rooftop Deck",
      "Concierge Service",
      "Finished Basement",
      "Private Terrace",
      "Water View",
      "Swimming Pool",
      "Central AC",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "300 Ocean Blvd, Miami, FL",
    lat: 25.74828705997647,
    lng: -80.18961901579382,
    description: "Fantastic condominium located in Miami.",
    link: "#"
  },
  {
    id: 50,
    city: "Miami",
    title: "House in Miami",
    price: 1779015,
    type: "House",
    area: 3006,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Elevator",
      "Newly Renovated",
      "Water View",
      "Walk-in Closets",
      "Rooftop Deck",
      "Secure Package Room",
      "Fenced Yard",
      "EV Charging Station",
      "Furnished",
      "High Ceilings",
      "Swimming Pool",
      "Central AC",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    address: "301 Ocean Blvd, Miami, FL",
    lat: 25.79628299024297,
    lng: -80.18126353266847,
    description: "Fantastic house located in Miami.",
    link: "#"
  },
  {
    id: 51,
    city: "Miami",
    title: "Condominium in Miami",
    price: 1140191,
    type: "Condominium",
    area: 3701,
    rooms: 7,
    bedrooms: 5,
    features: [
      "Private Terrace",
      "Doorman",
      "Finished Basement",
      "Newly Renovated",
      "Hardwood Floors",
      "Bike Storage",
      "Floor-to-Ceiling Windows",
      "Fireplace",
      "Concierge Service",
      "Smart Home System",
      "Furnished",
      "City View",
      "High Ceilings",
      "Walk-in Closets",
      "Central AC",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    address: "302 Ocean Blvd, Miami, FL",
    lat: 25.802329394899047,
    lng: -80.15511085112884,
    description: "Fantastic condominium located in Miami.",
    link: "#"
  },
  {
    id: 52,
    city: "Miami",
    title: "House in Miami",
    price: 1217984,
    type: "House",
    area: 2177,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Fireplace",
      "Hardwood Floors",
      "High Ceilings",
      "Walk-in Closets",
      "In-unit Washer/Dryer",
      "Central AC",
      "Balcony",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800",
    address: "303 Ocean Blvd, Miami, FL",
    lat: 25.79327210331766,
    lng: -80.14627039147781,
    description: "Fantastic house located in Miami.",
    link: "#"
  },
  {
    id: 53,
    city: "Miami",
    title: "Condominium in Miami",
    price: 1671453,
    type: "Condominium",
    area: 3759,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Smart Home System",
      "Newly Renovated",
      "Dishwasher",
      "Garage Parking",
      "Fitness Center",
      "Wheelchair Accessible",
      "Floor-to-Ceiling Windows",
      "Walk-in Closets",
      "Balcony",
      "High Ceilings",
      "EV Charging Station",
      "Doorman",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    address: "304 Ocean Blvd, Miami, FL",
    lat: 25.73817149214705,
    lng: -80.16061938369822,
    description: "Fantastic condominium located in Miami.",
    link: "#"
  },
  {
    id: 54,
    city: "Miami",
    title: "House in Miami",
    price: 1419828,
    type: "House",
    area: 1168,
    rooms: 7,
    bedrooms: 5,
    features: [
      "Hardwood Floors",
      "Rooftop Deck",
      "Balcony",
      "Furnished",
      "Wheelchair Accessible",
      "Fenced Yard",
      "Finished Basement",
      "Fireplace",
      "Spa & Sauna",
      "Dishwasher",
      "Water View",
      "High Ceilings",
      "Elevator",
      "Walk-in Closets",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
    address: "305 Ocean Blvd, Miami, FL",
    lat: 25.759646831710423,
    lng: -80.20037356780622,
    description: "Fantastic house located in Miami.",
    link: "#"
  },
  {
    id: 55,
    city: "Miami",
    title: "Condominium in Miami",
    price: 1300212,
    type: "Condominium",
    area: 3717,
    rooms: 5,
    bedrooms: 3,
    features: [
      "Newly Renovated",
      "Water View",
      "Wheelchair Accessible",
      "Concierge Service",
      "Hardwood Floors",
      "Swimming Pool",
      "City View",
      "Rooftop Deck",
      "Central AC",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "306 Ocean Blvd, Miami, FL",
    lat: 25.739764781412447,
    lng: -80.19252506330807,
    description: "Fantastic condominium located in Miami.",
    link: "#"
  },
  {
    id: 56,
    city: "Miami",
    title: "House in Miami",
    price: 1217311,
    type: "House",
    area: 977,
    rooms: 3,
    bedrooms: 1,
    features: [
      "Pet Friendly",
      "Home Office",
      "Garage Parking",
      "Finished Basement",
      "Central AC",
      "Swimming Pool",
      "Balcony",
      "Fitness Center",
      "Private Terrace",
      "Bike Storage",
      "Secure Package Room",
      "Rooftop Deck",
      "Solar Panels",
      "Wheelchair Accessible",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800",
    address: "307 Ocean Blvd, Miami, FL",
    lat: 25.809466670786154,
    lng: -80.19561975337662,
    description: "Fantastic house located in Miami.",
    link: "#"
  },
  {
    id: 57,
    city: "Miami",
    title: "Condominium in Miami",
    price: 1217771,
    type: "Condominium",
    area: 3167,
    rooms: 3,
    bedrooms: 1,
    features: [
      "Newly Renovated",
      "Walk-in Closets",
      "In-unit Washer/Dryer",
      "Pet Friendly",
      "Solar Panels",
      "Co-working Space",
      "Spa & Sauna",
      "Central AC",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
    address: "308 Ocean Blvd, Miami, FL",
    lat: 25.79595493803712,
    lng: -80.20297947711391,
    description: "Fantastic condominium located in Miami.",
    link: "#"
  },
  {
    id: 58,
    city: "Miami",
    title: "House in Miami",
    price: 411477,
    type: "House",
    area: 1140,
    rooms: 3,
    bedrooms: 1,
    features: [
      "Doorman",
      "Solar Panels",
      "Rooftop Deck",
      "Central AC",
      "Balcony",
      "Finished Basement",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
    address: "309 Ocean Blvd, Miami, FL",
    lat: 25.739711452095744,
    lng: -80.21544243173282,
    description: "Fantastic house located in Miami.",
    link: "#"
  },
  {
    id: 59,
    city: "Miami",
    title: "Condominium in Miami",
    price: 954404,
    type: "Condominium",
    area: 3045,
    rooms: 4,
    bedrooms: 2,
    features: [
      "Water View",
      "Balcony",
      "Furnished",
      "Fenced Yard",
      "Walk-in Closets",
      "Hardwood Floors",
      "Pet Friendly",
      "Rooftop Deck",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "3010 Ocean Blvd, Miami, FL",
    lat: 25.785912935371204,
    lng: -80.2233334237638,
    description: "Fantastic condominium located in Miami.",
    link: "#"
  },
  {
    id: 60,
    city: "Miami",
    title: "House in Miami",
    price: 1131988,
    type: "House",
    area: 2971,
    rooms: 7,
    bedrooms: 5,
    features: [
      "Fireplace",
      "Floor-to-Ceiling Windows",
      "Balcony",
      "Dishwasher",
      "Smart Home System",
      "City View",
      "Doorman",
      "Water View",
      "In-unit Washer/Dryer",
      "Central AC",
      "Elevator"
    ],
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=800",
    address: "3011 Ocean Blvd, Miami, FL",
    lat: 25.787252870776857,
    lng: -80.21165737940123,
    description: "Fantastic house located in Miami.",
    link: "#"
  },
  {
    id: 61,
    city: "Miami",
    title: "Condominium in Miami",
    price: 563523,
    type: "Condominium",
    area: 1242,
    rooms: 5,
    bedrooms: 3,
    features: [
      "High Ceilings",
      "Elevator",
      "Balcony",
      "Private Terrace",
      "Spa & Sauna",
      "Solar Panels",
      "Water View",
      "Fireplace",
      "Newly Renovated",
      "Floor-to-Ceiling Windows",
      "Central AC"
    ],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
    address: "3012 Ocean Blvd, Miami, FL",
    lat: 25.77309323632561,
    lng: -80.14775092291683,
    description: "Fantastic condominium located in Miami.",
    link: "#"
  },
  {
    id: 62,
    city: "Miami",
    title: "House in Miami",
    price: 1125543,
    type: "House",
    area: 2149,
    rooms: 7,
    bedrooms: 5,
    features: [
      "Smart Home System",
      "Water View",
      "Pet Friendly",
      "Garage Parking",
      "Walk-in Closets",
      "Swimming Pool",
      "Furnished",
      "Elevator",
      "Central AC",
      "Fireplace",
      "Balcony"
    ],
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
    address: "3013 Ocean Blvd, Miami, FL",
    lat: 25.717598133175606,
    lng: -80.17741681264965,
    description: "Fantastic house located in Miami.",
    link: "#"
  },
  {
    id: 63,
    city: "Miami",
    title: "Condominium in Miami",
    price: 1022574,
    type: "Condominium",
    area: 2219,
    rooms: 3,
    bedrooms: 1,
    features: [
      "Hardwood Floors",
      "In-unit Washer/Dryer",
      "Private Terrace",
      "Concierge Service",
      "Fitness Center",
      "Balcony",
      "Garage Parking",
      "Water View",
      "Central AC",
      "EV Charging Station",
      "Fireplace",
      "Pet Friendly",
      "Fenced Yard",
      "Wheelchair Accessible",
      "High Ceilings"
    ],
    image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
    address: "3014 Ocean Blvd, Miami, FL",
    lat: 25.762946064599753,
    lng: -80.18596971827682,
    description: "Fantastic condominium located in Miami.",
    link: "#"
  }
];